### ISSUE TITLE
FGPopupList+Monitor作用是什么？

### ISSUE THREAD

**Issue by JoshuaITChao** [FoneG/FGPopupScheduler#3]
为什么在添加的时候要先移除，原因或者逻辑是什么

**Comment by FoneG** [comment]
这里hook了<FGPopupView>的 `-dismiss `方法，目的是在弹窗移除的时候也能主动从list中移除，不需要外部再手动处理这部分逻辑。 都是为了使用者只需要考虑本身的业务逻辑。
