### ISSUE TITLE
tabbar下的首页全屏弹窗如何处理？

### ISSUE THREAD

**Issue by Engandend** [FoneG/FGPopupScheduler#6]
有这样一个场景，

tabbar里面嵌套2个界面。首页（1）、个人中心（2）

启动时，在首页有2个弹窗（弹窗1）、（弹窗2）这2个弹窗要铺满全屏（要遮挡住tabbar）

产品要求：点击弹窗1，跳转到二级界面，此时弹窗2不展示，从二级界面返回到首页，再弹出弹窗2

这种场景：应该如何处理？

**Comment by FoneG** [comment]
可以给弹窗2限定一个显示条件，譬如只能在首页才能出现。
